@hostname = http://localhost:3000/api
@contentType = application/json
@entryId = 650e94f0a18cedfcaba07438

### Add seed only for dev
GET {{hostname}}/seed

### GetEntries
GET {{hostname}}/entries

### GetEntryById
GET {{hostname}}/entries/{{entryId}}

### AddEntry
POST {{hostname}}/entries
content-type: {{contentType}}

{
    "description": "Hi from Perú"
}

### UpdateEntrybyId
PUT {{hostname}}/entries/{{entryId}}
content-type: {{contentType}}

{
    "description": "Hi from Perú - Lima"
}
